---
name: 'Run golangci-lint'
description: 'Official golangci-lint action with line-attached annotations for found issues, caching and parallel execution.'
author: 'golangci'
inputs:
  version:
    description: 'version of golangci-lint to use in form of v1.2.3'
    required: true
  args:
    description: 'golangci-lint command line arguments'
    default: ''
    required: false
  working-directory:
    description: 'golangci-lint working directory, default is project root'
    required: false

runs:
  using: 'node12'
  main: 'dist/run/index.js'
  post: 'dist/post_run/index.js'
branding:
  icon: 'shield'
  color: 'yellow'
